### ISSUE TITLE
编译过程出现下面错误提示，在app里调用出现不能打开某so文件。

### ISSUE THREAD

**Issue by ArlenWang** [bashen1/react-native-mbaichuan#1]
配置：
 "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-mbaichuan": "^1.0.2"
下面是运行编译提示的错误
> Task :react-native-mbaichuan:compileDebugJavaWithJavac
注: /Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/src/main/java/com/manmanbuy/mbaichuan/BCWebManager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/src/main/java/com/manmanbuy/mbaichuan/BCWebManager.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.impl.client.DefaultHttpClient` was not found, it is required for default or static interface methods desugaring of `org.apache.http.protocol.BasicHttpProcessor com.alipay.android.phone.mrpc.core.d.createHttpProcessor()`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.impl.client.DefaultRedirectHandler` was not found, it is required for default or static interface methods desugaring of `boolean com.alipay.android.phone.mrpc.core.e.isRedirectRequested(org.apache.http.HttpResponse, org.apache.http.protocol.HttpContext)`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.client.utils.URLEncodedUtils` was not found, it is required for default or static interface methods desugaring of `byte[] com.alipay.android.phone.mrpc.core.a.e.a()`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.params.HttpProtocolParams` was not found, it is required for default or static interface methods desugaring of `com.alipay.android.phone.mrpc.core.b com.alipay.android.phone.mrpc.core.b.a(java.lang.String)`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.client.params.HttpClientParams` was not found, it is required for default or static interface methods desugaring of `com.alipay.android.phone.mrpc.core.b com.alipay.android.phone.mrpc.core.b.a(java.lang.String)`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.conn.scheme.PlainSocketFactory` was not found, it is required for default or static interface methods desugaring of `com.alipay.android.phone.mrpc.core.b com.alipay.android.phone.mrpc.core.b.a(java.lang.String)`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.conn.params.ConnManagerParams` was not found, it is required for default or static interface methods desugaring of `com.alipay.android.phone.mrpc.core.b com.alipay.android.phone.mrpc.core.b.a(java.lang.String)`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.params.HttpProtocolParams` was not found, it is required for default or static interface methods desugaring of `com.alipay.sdk.net.b com.alipay.sdk.net.b.a()`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.conn.params.ConnManagerParams` was not found, it is required for default or static interface methods desugaring of `com.alipay.sdk.net.b com.alipay.sdk.net.b.a()`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.client.params.HttpClientParams` was not found, it is required for default or static interface methods desugaring of `com.alipay.sdk.net.b com.alipay.sdk.net.b.a()`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Type `org.apache.http.conn.scheme.PlainSocketFactory` was not found, it is required for default or static interface methods desugaring of `com.alipay.sdk.net.b com.alipay.sdk.net.b.a()`
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Interface `org.apache.http.client.HttpClient` not found. It's needed to make sure desugaring of `com.alipay.android.phone.mrpc.core.b` is correct. Desugaring will assume that this interface has no default method.
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Interface `org.apache.http.conn.ConnectionKeepAliveStrategy` not found. It's needed to make sure desugaring of `com.alipay.android.phone.mrpc.core.f` is correct. Desugaring will assume that this interface has no default method.
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Interface `org.apache.http.HttpRequestInterceptor` not found. It's needed to make sure desugaring of `com.alipay.android.phone.mrpc.core.c` is correct. Desugaring will assume that this interface has no default method.
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/alipaySingle-20160825.jar: D8: Interface `org.apache.http.client.HttpRequestRetryHandler` not found. It's needed to make sure desugaring of `com.alipay.android.phone.mrpc.core.ad` is correct. Desugaring will assume that this interface has no default method.
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/fastjson-1.2.9.jar: D8: Interface `javax.ws.rs.ext.MessageBodyReader` not found. It's needed to make sure desugaring of `com.alibaba.fastjson.support.jaxrs.FastJsonProvider` is correct. Desugaring will assume that this interface has no default method.
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/fastjson-1.2.9.jar: D8: Interface `javax.ws.rs.ext.MessageBodyWriter` not found. It's needed to make sure desugaring of `com.alibaba.fastjson.support.jaxrs.FastJsonProvider` is correct. Desugaring will assume that this interface has no default method.
/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/libs/fastjson-1.2.9.jar: D8: Type `org.springframework.util.CollectionUtils` was not found, it is required for default or static interface methods desugaring of `java.lang.Object com.alibaba.fastjson.support.spring.FastJsonJsonView.filterModel(java.util.Map)`

> Task :react-native-mbaichuan:transformNativeLibsWithStripDebugSymbolForDebug
/Users/mljfnn/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip:/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi-v7a/libsgsecuritybody.so: File format not recognized

Unable to strip library '1' due to error /Users/mljfnn/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip returned from '/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi-v7a/libsgsecuritybody.so', packaging it as is.
/Users/mljfnn/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip:/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi-v7a/libsgmain.so: File format not recognized

Unable to strip library '1' due to error /Users/mljfnn/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip returned from '/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi-v7a/libsgmain.so', packaging it as is.
Unable to strip library '/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi/libsgsecuritybody.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.
Unable to strip library '/Users/mljfnn/Desktop/demo/youhuigou_m/node_modules/react-native-mbaichuan/android/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi/libsgmain.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.

> Task :app:transformNativeLibsWithStripDebugSymbolForDebug
/Users/mljfnn/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip:/Users/mljfnn/Desktop/demo/youhuigou_m/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi-v7a/libsgsecuritybody.so: File format not recognized

Unable to strip library '1' due to error /Users/mljfnn/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip returned from '/Users/mljfnn/Desktop/demo/youhuigou_m/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi-v7a/libsgsecuritybody.so', packaging it as is.
/Users/mljfnn/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip:/Users/mljfnn/Desktop/demo/youhuigou_m/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi-v7a/libsgmain.so: File format not recognized

Unable to strip library '1' due to error /Users/mljfnn/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip returned from '/Users/mljfnn/Desktop/demo/youhuigou_m/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi-v7a/libsgmain.so', packaging it as is.
Unable to strip library '/Users/mljfnn/Desktop/demo/youhuigou_m/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi/libsgsecuritybody.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.
Unable to strip library '/Users/mljfnn/Desktop/demo/youhuigou_m/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi/libsgmain.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.

**Comment by ArlenWang** [comment]
init操作时错误
`07-05 12:00:06.356: E/AliBC_Trade[3.1.1.219](15506): AppMonitor -> [com.alibaba.baichuan.trade.common.adapter.security.c.a:70] AlibcSecurity init 
07-05 12:00:06.356: E/AliBC_Trade[3.1.1.219](15506): ErrorCode = 103
07-05 12:00:06.356: E/AliBC_Trade[3.1.1.219](15506): com.alibaba.wireless.security.open.SecException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.mlj.youhuigou/app_SGLib/libsgmainso-5.1.81.so" has unexpected e_machine: 40 (EM_ARM)
07-05 12:00:06.356: E/AliBC_Trade[3.1.1.219](15506): 	at com.alibaba.wireless.security.mainplugin.SecurityGuardMainPlugin.onPluginLoaded(Unknown Source:85)`

**Comment by bashen1** [comment]
可以试下新的SDK
