### ISSUE TITLE
Could not find com.taobao.androidxxxxxx

### ISSUE THREAD

**Issue by qg-hs** [bashen1/react-native-mbaichuan#12]
Could not determine the dependencies of task ':react-native-mbaichuan:compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':react-native-mbaichuan:releaseCompileClasspath'.
   > Could not find com.taobao.android:securityguardaar3:5.4.171.
     Required by:
         project :react-native-mbaichuan
   > Could not find com.taobao.android:securitybodyaar3:5.4.99.
     Required by:
         project :react-native-mbaichuan
   > Could not find com.taobao.android:avmpaar3:5.4.36.
     Required by:
         project :react-native-mbaichuan
   > Could not find com.taobao.android:sgmiddletieraar3:5.4.9.
     Required by:
         project :react-native-mbaichuan
   > Could not find com.taobao.android:mtopsdk_allinone_open:3.1.2.5.
     Required by:
         project :react-native-mbaichuan
   > Could not find com.alibaba.sdk.android:alibc_link_partner:4.1.15.
     Required by:
         project :react-native-mbaichuan

**Comment by bashen1** [comment]
需要操作以下步骤
Android
打开android/bulid.gradle，添加以下仓库

```
allprojects {
    repositories {
        ·····
        maven {
            url "http://repo.baichuan-android.taobao.com/content/groups/BaichuanRepositories/"
        }
    }
}
```
