### ISSUE TITLE
Could not resolve all task dependencies for configuration ':react-native-mbaichuan:debugCompileClasspath'.

### ISSUE THREAD

**Issue by darryl-tan** [bashen1/react-native-mbaichuan#13]
首先感谢兄弟能提供这玩意，我们做reactnative 的，真的去写安卓和调用原生模块，真的很难受，新手路过。
我几乎看了所有的git和百度，关于阿里百川的，我最多用安卓的原生包成功使用了电商sdk，但是用rn 的包，无论怎么样都错。
然后git上安装npm，还是通过不了。麻烦了，我这个愿意付费咨询。我QQ邮箱 55473203@qq.com
问题:无论是vscode报错和AS Sycn  都一样的报错。
vs：
`* What went wrong:
Could not determine the dependencies of task ':react-native-mbaichuan:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-mbaichuan:debugCompileClasspath'.
   > Could not find com.taobao.android:securityguardaar3:5.4.171.
     Required by:
         project :react-native-mbaichuan
   > Could not find com.taobao.android:securitybodyaar3:5.4.99.
     Required by:
         project :react-native-mbaichuan
   > Could not find com.taobao.android:avmpaar3:5.4.36.
     Required by:
         project :react-native-mbaichuan
   > Could not find com.taobao.android:sgmiddletieraar3:5.4.9.
     Required by:
         project :react-native-mbaichuan
   > Could not find com.taobao.android:mtopsdk_allinone_open:3.1.2.5.
     Required by:
         project :react-native-mbaichuan
   > Could not find com.alibaba.sdk.android:alibc_link_partner:4.1.15.
     Required by:
         project :react-native-mbaichuan

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log 
output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s`

安卓报错：
`Fail to resolve:com.taobao.android.secuirtyguardarr 3：5.4.171 <a href="XXXXX">`

我配置了你说的maven，路径对的
android>build.gradle
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
        maven {
            url "http://repo.baichuan-android.taobao.com/content/groups/BaichuanRepositories/"
        }
    }
}
`
AS显示就是 build.gradle(Project)
期待你的回复
期待你的回复
期待你的回复
期待你的回复
期待你的回复
期待你的回复

**Comment by darryl-tan** [comment]
作者很认真热情的帮我了，感谢。
#distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip
distributionUrl=https\://services.gradle.org/distributions/gradle-5.5-all.zip
在 gradle-wrapper.properties 里面

**Comment by tanjwGit** [comment]
@bashen1 
当升级react-native至0.64时， rn官方`distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip`, 但是
`react-native-mbaichuan`必须使用5.5版本， 修改为5.5后，版本检查器提示最低版本为6.5， 错误如下：
```
What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 6.5. Current version is 5.5. If using the gradle wrapper, try editing the distributionUrl in /Users/zhangchao/Work/waitpay/android/gradle/wrapper/gradle-wrapper.properties to gradle-6.5-all.zip
```

请升级百川库

**Comment by tanjiaweiGitHub** [comment]
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 6.5. Current version is 5.5. If using the gradle wrapper, try editing the distributionUrl in /Users/zhangchao/Work/waitpay/android/gradle/wrapper/gradle-wrapper.properties to gradle-6.5-all.zip
```

请升级百川版本

**Comment by bashen1** [comment]
> @bashen1 当升级react-native至0.64时， rn官方`distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip`, 但是 `react-native-mbaichuan`必须使用5.5版本， 修改为5.5后，版本检查器提示最低版本为6.5， 错误如下：
> 
> ```
> What went wrong:
> A problem occurred evaluating project ':app'.
> > Failed to apply plugin [id 'com.android.internal.version-check']
>    > Minimum supported Gradle version is 6.5. Current version is 5.5. If using the gradle wrapper, try editing the distributionUrl in /Users/zhangchao/Work/waitpay/android/gradle/wrapper/gradle-wrapper.properties to gradle-6.5-all.zip
> ```
> 
> 请升级百川库
已升级至最新版本，安全图片记得用v6
