### ISSUE TITLE
AlibabaAuthSDK/ALBBSDK.h' file not found

### ISSUE THREAD

**Issue by 1512751361** [bashen1/react-native-mbaichuan#3]
## 你的运行环境

* 插件版本:
* react-native 版本：0.60.5
* react-native-mbaichuan 版本：2.0.2

## Debug logs

包括 Android 或 iOS 的日志：
ios 报错
AlibabaAuthSDK/ALBBSDK.h' file not found

**Comment by bashen1** [comment]
iOS的SDK 下载本git项目中的，替换掉npm下载的
