### ISSUE TITLE
ld: framework not found UTDID

### ISSUE THREAD

**Issue by 1512751361** [bashen1/react-native-mbaichuan#5]
## 你的运行环境

* 插件版本:
* react-native 版本：0.60.5
* react-native-mbaichuan 版本：3.0.1

## Debug logs

包括 Android 或 iOS 的日志：
ios 报错
ld: framework not found UTDID
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bashen1** [comment]
```
NPM 安装完以后，必须下载本仓库中的百川SDK（iOS），由于百川SDK中用了SystemLink，NPM中的百川SDK包不完整，Android不受影响
````
看说明文档
